export const SEGMENT_PLAYBOOKS = [
  {
    code: "ATS",
    title: "ATS / Recruitment OS",
    target: "Кадровые агентства и компании с 5–20+ рекрутерами, уже использующие Huntflow/Potok/Talantix/FriendWork.",
    lpr: "Founder агентства / HRD / Head of Talent Acquisition / Head of Recruitment",
    firstQuestion: "Сколько рекрутеров реально работает в ATS, когда продление и что в текущей системе раздражает больше всего?",
    demo: "Не рисовать абстрактный интерфейс. Попросить экспорт 100–500 кандидатов и показать их поиск, историю, вакансии, pipeline и AI-summary в нашем прототипе.",
    offer: "Бесплатная миграция + 30 дней параллельной работы + 45–60% текущего подтвержденного TCO + фиксированная цена на 2–3 года.",
    buildGate: "Строить ATS, только если минимум 3 demo commitments, 2 согласия дать экспорт и 1 deposit commitment.",
    steps: [
      "Подтвердить ATS публичным источником; не считать технологический сигнал подтверждением от клиента.",
      "Найти конкретного HRD/Head of Recruitment, а в агентстве — сразу founder/CEO.",
      "Получить число платных рекрутерских мест и дату renewal.",
      "На discovery выяснить: импорт резюме, job boards, WhatsApp/Telegram, hiring managers, отчеты, API, SSO и персональные данные.",
      "Попросить показать счет/договор или хотя бы точный annual TCO.",
      "Предложить migration test на копии 100–500 кандидатов без отключения текущей ATS.",
      "Demo строить на их данных: поиск, карточка, история, pipeline, AI ranking/summary.",
      "КП давать только после TCO: миграция + onboarding + annual prepaid license.",
      "Депозит засчитывать полностью в первый год лицензии.",
      "После первого сильного клиента использовать его как reference и атаковать похожие recruitment teams.",
    ],
  },
  {
    code: "LMS",
    title: "Corporate LMS",
    target: "Сети с 300–5000+ сотрудниками: retail, restaurants, telecom, manufacturing, logistics, banks — особенно с постоянным onboarding и аттестациями.",
    lpr: "HRD / Head of L&D / Corporate University / COO; IT подключается после business interest.",
    firstQuestion: "Сколько сотрудников реально обучается ежемесячно, сколько стоит LMS в год и сколько часов команда тратит на создание/обновление курсов?",
    demo: "Взять один реальный PDF/PPT/регламент клиента и за demo автоматически превратить его в курс + тест + отчет руководителя.",
    offer: "Annual prepaid 45–60% текущего TCO, миграция пользователей/SCORM/курсов, RU/KZ, AI course builder, 30 дней parallel run.",
    buildGate: "Побеждает, если 3 компании дают материалы для demo, 2 готовы мигрировать часть курсов и 1 готова к депозиту.",
    steps: [
      "Выбрать компании, где обучение влияет на операционные стандарты, а не используется раз в год.",
      "Подтвердить текущую LMS и примерный размер обучаемого штата.",
      "Выйти на L&D/HRD, а не начинать с IT procurement.",
      "Выяснить annual TCO, renewal, активных пользователей и платные add-ons.",
      "Собрать must-have: SCORM, тесты, certificates, оргструктура, роли, SSO, API, мобильность, отчеты.",
      "Получить один реальный обучающий материал и сделать персональный AI-demo.",
      "Показать руководителю не интерфейс, а сокращение времени выпуска курса и стоимость на сотрудника.",
      "Попросить экспорт пользователей/курсов для migration test.",
      "КП: migration + onboarding + parallel run + annual license; цену считать от подтвержденного TCO.",
      "Банки/крупное производство вести параллельно как whale pipeline, но cash сентября не строить только на них.",
    ],
  },
  {
    code: "CX",
    title: "Helpdesk / Omnichannel CX",
    target: "Ecommerce, delivery, fintech, telecom, travel и сервисы с 20–200+ агентами и несколькими каналами поддержки.",
    lpr: "Customer Service Director / Contact Center Director / Head of CX / COO; затем CIO/IT Security.",
    firstQuestion: "Сколько операторов и отдельных подписок сейчас обслуживают email, WhatsApp, Instagram, Telegram, телефонию и AI — и сколько весь стек стоит в год?",
    demo: "Импортировать небольшой набор тикетов/диалогов и показать unified inbox, routing, SLA, AI-summary, suggested reply, QA и аналитику.",
    offer: "Не только дешевле Zendesk/Usedesk: заменить 3–4 счета одним Customer OS, сохранив каналы и SLA; 30 дней parallel run.",
    buildGate: "Нужны минимум 2 компании, готовые дать исторические тикеты/API sample, и 1 deposit commitment; иначе интеграционный риск слишком высок.",
    steps: [
      "Считать не только цену helpdesk, а полный TCO: каналы, телефония, WhatsApp BSP, AI, QA, reporting.",
      "Подтвердить число агентов и каналы; без этого ценовая атака бессмысленна.",
      "Выходить на CX/Contact Center, а не продавать сначала CIO.",
      "Discovery: SLA, routing, escalation, macros, knowledge base, voice, API, audit, retention, language requirements.",
      "Попросить реальную месячную стоимость всего support stack и дату renewal основных контрактов.",
      "Выбрать 1–2 канала для безопасного parallel pilot, не мигрировать весь contact center сразу.",
      "Demo на реальных обезличенных тикетах: AI summary, category, sentiment, reply, QA score.",
      "КП строить как consolidated TCO saving, а не как дешевую лицензию одного helpdesk.",
      "Для enterprise заранее зафиксировать security/SSO/data residency требования до разработки.",
      "Победу засчитывать только после готовности клиента дать данные и оплатить пилот/депозит.",
    ],
  },
  {
    code: "CDP",
    title: "CDP / Marketing Automation",
    target: "Mature ecommerce/retail с большой клиентской базой, loyalty, email/SMS/push и давно работающим Mindbox/аналогом.",
    lpr: "CMO / CRM Director / Ecommerce Director / Head of Retention; CTO/CIO подключаются для data layer.",
    firstQuestion: "Какая часть выручки реально зависит от текущих триггеров/loyalty, сколько стоит платформа вместе с сообщениями и когда renewal?",
    demo: "Не клонировать весь Mindbox заранее. Воспроизвести 2–3 самых денежных сценария клиента на параллельном event stream и сравнить результат.",
    offer: "Parity по критичным journeys + 30 дней parallel measurement + более низкий TCO. Цена сама по себе не должна заставлять клиента рисковать retention revenue.",
    buildGate: "Строить CDP только при whale commitment: доступ к схеме событий/сегментов, конкретные journeys для parity test и депозит/LOI.",
    steps: [
      "Искать старых/mature пользователей, а не компании, только что внедрившие платформу.",
      "Подтвердить текущий CDP и понять объем базы, каналы и основные платные модули.",
      "Выйти на CRM/Retention/CMO и выяснить 3 сценария, которые дают основную ценность.",
      "Получить annual TCO и renewal; отдельно посчитать messaging и add-ons.",
      "Зафиксировать event schema, identity resolution, loyalty, segmentation, frequency caps, experiments и reporting must-have.",
      "Не обещать полную миграцию сразу: предложить shadow/parallel event stream.",
      "Скопировать 2–3 revenue-critical journeys и провести parity test.",
      "КП делать только после доказательства parity; скидка должна компенсировать switching risk.",
      "Если клиент не дает event/data sample и не готов к платному pilot — сегмент не получает разработку.",
      "Один whale с сильным commitment может перебить остальные сегменты по аукциону, но только фактами, не потенциальным чеком.",
    ],
  },
] as const;
