export const FUNNEL_STAGES = [
  { key: "research", label: "1. Исследование" },
  // LOST стоит до квалификационных этапов намеренно: это терминальный архивный статус,
  // поэтому getStageGate не требует от отказа TCO/demo/deposit.
  { key: "lost", label: "× LOST / архив" },
  { key: "lpr_found", label: "2. ЛПР найден" },
  { key: "contacted", label: "3. Первый контакт" },
  { key: "discovery", label: "4. Discovery с ЛПР" },
  { key: "tco_confirmed", label: "5. TCO / renewal подтверждены" },
  { key: "demo", label: "6. Demo согласовано" },
  { key: "migration_test", label: "7. Тест миграции" },
  { key: "offer", label: "8. КП отправлено" },
  { key: "deposit", label: "9. Депозит" },
  { key: "pilot", label: "10. Пилот" },
  { key: "won", label: "11. WON" },
] as const;

export type FunnelStage = (typeof FUNNEL_STAGES)[number]["key"];

export const SEGMENT_TEMPLATES = [
  {
    code: "ATS",
    name: "ATS / Recruitment OS",
    priority: 1,
    software: "Huntflow, Potok, Talantix, FriendWork",
    thesis: "Быстрый перехват: цена растет за рекрутера, база переносима, ЛПР доступен, demo можно делать на данных клиента.",
    benchmark: "Huntflow KZ 2026: Professional 480 000 ₸/рекрутер/год; Maximum 660 000 ₸/рекрутер/год.",
    migration_ease: 9,
    build_ease: 9,
  },
  {
    code: "LMS",
    name: "Corporate LMS",
    priority: 2,
    software: "iSpring Learn, SOHO.LMS, Teachbase, Moodle-интеграторы",
    thesis: "Высокий годовой чек у компаний с 300–5000 сотрудников; курсы и пользователи мигрируют без остановки основного бизнеса.",
    benchmark: "SOHO.LMS KZ 2026: 500 — 310 990 ₸/мес; 1000 — 491 990 ₸/мес; 2000 — 680 990 ₸/мес при годовой оплате.",
    migration_ease: 8,
    build_ease: 8,
  },
  {
    code: "CX",
    name: "Helpdesk / Omnichannel CX",
    priority: 3,
    software: "Zendesk, Usedesk, Freshdesk, Intercom",
    thesis: "Часто можно заменить несколько счетов одним Customer OS: helpdesk + WhatsApp + social + AI + аналитика.",
    benchmark: "Цель: команды от 20 операторов. Считать полный TCO стека, а не только лицензию helpdesk.",
    migration_ease: 6,
    build_ease: 6,
  },
  {
    code: "CDP",
    name: "CDP / Marketing Automation",
    priority: 4,
    software: "Mindbox, Maestra, Bloomreach, Altcraft",
    thesis: "Самые крупные контракты, но высокий switching risk. Строить только под сильный commitment и parity-test на реальных journeys.",
    benchmark: "Искать mature ecommerce/retail с большой базой и близким renewal; не тратить сентябрь на свежие внедрения.",
    migration_ease: 4,
    build_ease: 4,
  },
] as const;

export type SegmentTemplateCode = (typeof SEGMENT_TEMPLATES)[number]["code"];

export type SeedCompany = {
  name: string;
  segment_code: SegmentTemplateCode;
  tier: "A" | "B" | "C";
  current_software: string;
  evidence_url: string;
  evidence_note: string;
  evidence_confidence: "high" | "medium" | "low";
  decision_maker_role: string;
  why_now: string;
  estimated_tco_kzt?: number;
};

export const COMPANY_TEMPLATES: SeedCompany[] = [
  {
    name: "Kompra Group / Pro People",
    segment_code: "ATS",
    tier: "A",
    current_software: "Huntflow",
    evidence_url: "https://astana.careerist.ru/vakansii/it-rekruter-pro-people-85162478.html",
    evidence_note: "Публичная вакансия прямо указывала ведение базы кандидатов в Huntflow; подтвердить текущий контракт перед оффером.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / Head of Recruitment / CEO",
    why_now: "Доступный ЛПР, IT-среда, быстрый migration test.",
  },
  {
    name: "RecruitHub",
    segment_code: "ATS",
    tier: "A",
    current_software: "Huntflow + Notion",
    evidence_url: "https://hirehi.ru/recruiting/nachinaiushchii-hr-rekruter-76538",
    evidence_note: "В вакансии от 14.08.2026 указаны Huntflow и Notion.",
    evidence_confidence: "high",
    decision_maker_role: "Founder / Head of Recruitment",
    why_now: "Recruitment — ядро бизнеса; короткая цепочка принятия решения.",
  },
  {
    name: "Kolesa Group",
    segment_code: "ATS",
    tier: "A",
    current_software: "Huntflow",
    evidence_url: "https://www.remocate.app/",
    evidence_note: "Публичный recruitment-сигнал Huntflow; найти и сохранить актуальное прямое доказательство перед звонком.",
    evidence_confidence: "medium",
    decision_maker_role: "HRD / Head of Talent Acquisition",
    why_now: "Очень сильный reference-клиент при успешном перехвате.",
  },
  {
    name: "SR Technologies",
    segment_code: "ATS",
    tier: "A",
    current_software: "Huntflow + Notion",
    evidence_url: "https://hh.kz/",
    evidence_note: "В публичной вакансии фигурировали Huntflow и Notion; перепроверить актуальный URL.",
    evidence_confidence: "medium",
    decision_maker_role: "HRD / Recruitment Lead / CEO",
    why_now: "Вероятно короче sales cycle; подходит для первого paid pilot.",
  },
  {
    name: "ROGII",
    segment_code: "ATS",
    tier: "A",
    current_software: "Huntflow + BambooHR",
    evidence_url: "https://www.linkedin.com/",
    evidence_note: "Публичный HR-сигнал связки Huntflow + BambooHR; подтвердить текущий стек.",
    evidence_confidence: "medium",
    decision_maker_role: "HRD / Head of People",
    why_now: "Возможность расширить ATS до HRIS и увеличить ACV.",
  },
  {
    name: "AB Restaurants",
    segment_code: "LMS",
    tier: "A",
    current_software: "iSpring",
    evidence_url: "https://asiacrm.kz/ispring/",
    evidence_note: "Публично указан среди клиентов iSpring у партнера в Казахстане.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / Head of L&D / COO",
    why_now: "Большой линейный штат, постоянный onboarding и стандарты по сети.",
  },
  {
    name: "Freedom Mobile",
    segment_code: "LMS",
    tier: "A",
    current_software: "iSpring",
    evidence_url: "https://asiacrm.kz/ispring/",
    evidence_note: "Публично указан среди клиентов iSpring у партнера в Казахстане.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / L&D Director / Retail Director",
    why_now: "Ритейл требует регулярного обучения продуктам и продавцов.",
  },
  {
    name: "Kazakh Tourism",
    segment_code: "LMS",
    tier: "A",
    current_software: "iSpring",
    evidence_url: "https://asiacrm.kz/ispring/",
    evidence_note: "Публично указан среди клиентов iSpring у партнера в Казахстане.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / L&D / Digital Director",
    why_now: "Подтвержденный публичный сигнал и потенциально доступнее ЛПР, чем в банках.",
  },
  {
    name: "Kazakhmys",
    segment_code: "LMS",
    tier: "B",
    current_software: "iSpring",
    evidence_url: "https://asiacrm.kz/ispring/",
    evidence_note: "Публично указан среди клиентов iSpring у партнера в Казахстане.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / Corporate University / Procurement",
    why_now: "Большой чек, но длинные security/procurement — whale pipeline, не основа сентября.",
  },
  {
    name: "ForteBank",
    segment_code: "LMS",
    tier: "B",
    current_software: "iSpring",
    evidence_url: "https://asiacrm.kz/ispring/",
    evidence_note: "Публично указан среди клиентов iSpring у партнера в Казахстане.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / L&D / CIO / Procurement",
    why_now: "Высокий потенциальный TCO; цикл длиннее из-за банковских требований.",
  },
  {
    name: "Bereke Bank",
    segment_code: "LMS",
    tier: "B",
    current_software: "iSpring",
    evidence_url: "https://asiacrm.kz/ispring/",
    evidence_note: "Публично указан среди клиентов iSpring у партнера в Казахстане.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / L&D / CIO / Procurement",
    why_now: "Высокий потенциал, но не рассчитывать только на эту сделку до 30.09.",
  },
  {
    name: "Kaspi.kz",
    segment_code: "LMS",
    tier: "C",
    current_software: "iSpring",
    evidence_url: "https://asiacrm.kz/ispring/",
    evidence_note: "Публично указан среди клиентов iSpring у партнера в Казахстане.",
    evidence_confidence: "high",
    decision_maker_role: "HRD / L&D / Procurement",
    why_now: "Сильнейший reference, но высокий enterprise barrier и сильная внутренняя разработка.",
  },
  {
    name: "Hasel Kazakhstan",
    segment_code: "CX",
    tier: "A",
    current_software: "Zendesk",
    evidence_url: "https://storeleads.app/reports/technology/Zendesk/country/KZ",
    evidence_note: "Tech-detection сигнал Zendesk; обязательно подтвердить у клиента и выяснить число агентов.",
    evidence_confidence: "medium",
    decision_maker_role: "Head of Customer Service / CX Director / COO",
    why_now: "Ecommerce с потенциально более коротким enterprise cycle, чем у крупнейших сетей.",
  },
  {
    name: "Technodom",
    segment_code: "CX",
    tier: "B",
    current_software: "Zendesk",
    evidence_url: "https://storeleads.app/reports/technology/Zendesk/country/KZ",
    evidence_note: "Tech-detection сигнал Zendesk; подтвердить текущий стек и контракт.",
    evidence_confidence: "medium",
    decision_maker_role: "CX Director / Contact Center Director / CIO",
    why_now: "Очень большой потенциальный TCO, но enterprise sales cycle длиннее.",
  },
  {
    name: "Beeline Kazakhstan",
    segment_code: "CX",
    tier: "B",
    current_software: "Usedesk",
    evidence_url: "https://blog.usedesk.com/clients/beelinekz",
    evidence_note: "Публичный кейс Usedesk подтверждает использование на момент кейса; перед атакой проверить текущий статус.",
    evidence_confidence: "high",
    decision_maker_role: "Customer Service Director / Contact Center / CIO / Procurement",
    why_now: "Доказывает масштаб экономики сегмента, но вероятен тендер.",
  },
  {
    name: "KIMEX",
    segment_code: "CDP",
    tier: "A",
    current_software: "Mindbox",
    evidence_url: "https://storeleads.app/reports/technology/Mindbox/country/KZ",
    evidence_note: "Tech-detection сигнал Mindbox; выяснить, как давно используется и когда renewal.",
    evidence_confidence: "medium",
    decision_maker_role: "CMO / CRM Director / Ecommerce Director / CIO",
    why_now: "Retail + mature marketing automation; хороший баланс чека и доступности ЛПР.",
  },
  {
    name: "Meloman / MARWIN",
    segment_code: "CDP",
    tier: "A",
    current_software: "Mindbox",
    evidence_url: "https://storeleads.app/reports/technology/Mindbox/country/KZ",
    evidence_note: "Tech-detection сигнал Mindbox на брендах; проверить возможность multi-brand договора.",
    evidence_confidence: "medium",
    decision_maker_role: "CMO / CRM Lead / Ecommerce Director",
    why_now: "Потенциально один multi-brand контракт вместо двух отдельных продаж.",
  },
  {
    name: "Mark Formelle Kazakhstan",
    segment_code: "CDP",
    tier: "A",
    current_software: "Mindbox",
    evidence_url: "https://storeleads.app/reports/technology/Mindbox/country/KZ",
    evidence_note: "Tech-detection сигнал Mindbox; подтвердить контракт и maturity.",
    evidence_confidence: "medium",
    decision_maker_role: "CMO / CRM Lead / Ecommerce Director",
    why_now: "Fashion retail: частые покупки, loyalty, retention, персонализация.",
  },
  {
    name: "Arbuz.kz",
    segment_code: "CDP",
    tier: "B",
    current_software: "Mindbox",
    evidence_url: "https://mindbox.ru/journal/cases/arbuz-kz/",
    evidence_note: "Есть публичный клиентский кейс Mindbox; перед контактом проверить актуальность стека.",
    evidence_confidence: "high",
    decision_maker_role: "CMO / CRM Director / Product / CIO",
    why_now: "Продавать parity + AI + TCO, а не только низкой ценой: система уже доказала клиенту бизнес-ценность.",
  },
];

export const AUCTION_WIN_CONDITIONS = {
  dm_conversations: 10,
  competitor_confirmed: 5,
  demo_committed: 3,
  migration_data_committed: 2,
  deposit_committed: 1,
};
