// Реестр источников сигналов (коннекторов). Используется будущей версией
// app/sources/page.tsx. Поля строго соответствуют типу SourceConnector
// из lib/types.ts — не переименовывать.

import { SourceConnector } from "./types";

export const sources: SourceConnector[] = [
  // --- базовые источники, уже существующие на демо-странице app/sources/page.tsx ---
  {
    key: "pabliki_site",
    name: "Сайт Pabliki.kz (webhooks)",
    category: "owned",
    status: "mock",
    mode: "auto",
    reliability: 1.0,
    last_run_at: "2026-06-29T09:12:00+06:00",
    next_run_at: null,
    required_env_vars: [],
    count: 68,
    notes: "Заявки с сайта Pabliki.kz. Вебхук-приёмник заглушен — пока работает на тестовых данных, реальный приём не подключён.",
  },
  {
    key: "google_places",
    name: "Google Places",
    category: "directories",
    status: "pending_access",
    mode: "auto",
    reliability: 0.8,
    last_run_at: "2026-06-29T08:40:00+06:00",
    next_run_at: null,
    required_env_vars: ["GOOGLE_PLACES_API_KEY"],
    count: 164,
    notes: "Новые точки/филиалы по справочнику. Ждёт выдачи API-ключа.",
  },
  {
    key: "2gis",
    name: "2GIS",
    category: "directories",
    status: "pending_access",
    mode: "semi",
    reliability: 0.75,
    last_run_at: "2026-06-29T08:10:00+06:00",
    next_run_at: null,
    required_env_vars: ["TWOGIS_API_KEY"],
    count: 102,
    notes: "Карточки компаний и новые заведения. Ждёт доступа к API 2GIS.",
  },
  {
    key: "rss",
    name: "Новости / RSS",
    category: "news",
    status: "mock",
    mode: "auto",
    reliability: 0.6,
    last_run_at: "2026-06-29T07:55:00+06:00",
    next_run_at: "2026-06-29T13:55:00+06:00",
    required_env_vars: [],
    count: 81,
  },
  {
    key: "wordstat",
    name: "Поисковые тренды / Wordstat",
    category: "trends",
    status: "mock",
    mode: "semi",
    reliability: 0.55,
    last_run_at: "2026-06-28T18:00:00+06:00",
    next_run_at: null,
    required_env_vars: [],
    count: 22,
  },
  {
    key: "meta_ads",
    name: "Meta Ad Library",
    category: "ads",
    status: "pending_access",
    mode: "semi",
    reliability: 0.7,
    last_run_at: null,
    next_run_at: null,
    required_env_vars: ["META_ACCESS_TOKEN", "META_AD_ACCOUNT_ID"],
    count: 0,
    notes: "Компании с активной рекламой в Meta — явный признак бюджета. Требует доступа к Meta API.",
  },
  {
    key: "instagram",
    name: "Instagram (бизнес-аккаунты)",
    category: "social",
    status: "pending_access",
    mode: "semi",
    reliability: 0.5,
    last_run_at: null,
    next_run_at: null,
    required_env_vars: ["INSTAGRAM_ACCESS_TOKEN"],
    count: 0,
  },
  {
    key: "telegram",
    name: "Telegram-каналы",
    category: "social",
    status: "pending_access",
    mode: "semi",
    reliability: 0.55,
    last_run_at: null,
    next_run_at: null,
    required_env_vars: ["TELEGRAM_BOT_TOKEN"],
    count: 0,
  },
  {
    key: "goszakup",
    name: "Госзакупки KZ (goszakup.gov.kz)",
    category: "government",
    status: "pending_access",
    mode: "auto",
    reliability: 0.85,
    last_run_at: null,
    next_run_at: null,
    required_env_vars: ["GOSZAKUP_API_TOKEN"],
    count: 0,
    notes: "Тендеры и госзакупки на рекламные/маркетинговые услуги.",
  },
  {
    key: "csv_import",
    name: "Excel/CSV импорт",
    category: "manual",
    status: "mock",
    mode: "manual",
    reliability: 0.65,
    last_run_at: "2026-06-28T14:20:00+06:00",
    next_run_at: null,
    required_env_vars: [],
    count: 47,
  },
  {
    key: "manual",
    name: "Ручное добавление",
    category: "manual",
    status: "active",
    mode: "manual",
    reliability: 0.7,
    last_run_at: "2026-06-29T10:05:00+06:00",
    next_run_at: null,
    required_env_vars: [],
    count: 9,
  },

  // --- новые источники ---
  {
    key: "old_clients_import",
    name: "Импорт старых клиентов",
    category: "manual",
    status: "mock",
    mode: "manual",
    reliability: 0.6,
    last_run_at: "2026-06-20T11:00:00+06:00",
    next_run_at: null,
    required_env_vars: [],
    count: 31,
    notes: "Реактивация клиентов из истории сделок агентства.",
  },
  {
    key: "hiring_signals",
    name: "Сигналы найма (вакансии)",
    category: "hiring",
    status: "mock",
    mode: "semi",
    reliability: 0.5,
    last_run_at: "2026-06-27T09:00:00+06:00",
    next_run_at: "2026-06-30T09:00:00+06:00",
    required_env_vars: [],
    count: 18,
    notes: "Активный набор сотрудников как признак роста/открытия точек.",
  },
  {
    key: "events",
    name: "Мероприятия / выставки",
    category: "events",
    status: "mock",
    mode: "semi",
    reliability: 0.5,
    last_run_at: "2026-06-22T10:00:00+06:00",
    next_run_at: null,
    required_env_vars: [],
    count: 9,
    notes: "Анонсы открытий, выставок, ярмарок — повод для размещения.",
  },
  {
    key: "reviews",
    name: "Отзывы (2GIS / Google)",
    category: "reputation",
    status: "mock",
    mode: "auto",
    reliability: 0.45,
    last_run_at: "2026-06-26T08:00:00+06:00",
    next_run_at: null,
    required_env_vars: [],
    count: 27,
    notes: "Всплеск новых отзывов как индикатор активности/роста бизнеса.",
  },
];
